### ISSUE TITLE
USER STORY: Navigate the site

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#1]
As a shopper **I can** navigate the site easily and intuitively **so that** I can easily find my way around the site.

Acceptance Criteria: Users can easily access all pages of the site from the navigation menu on mobile and large screen sizes.

#Tasks

- [x] build navigation menu
- [x] add urls & test all links
- [x] style the nav links

**Comment by DaveCaulfield** [comment]
#26
