### ISSUE TITLE
USER STORY: Personalised profile

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#11]
As a **site user** I can **have a personalized profile** so that **I can view my order history and save billing information**.

**Acceptance Criteria**: Users can view their order history in their personal profile page

#27 EPIC 2 Account Registration & Login

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create checkout app and models
- [x] create Views and templates
- [x] create an order history model
- [x] add order history to display in profile page
