### ISSUE TITLE
USER STORY: Select a category

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#15]
As a **shopper** I can **select a category of the product** so that **I can easily filter my searches**

**Acceptance Criteria**: Users can select a category the online shop

#28  EPIC 3 Search & sort products

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] add category model and create categories.
- [x] add the categories feature into all_products view
- [x] add categories into url links and test
