### ISSUE TITLE
USER STORY: Add item to shopping cart

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#17]
As a **shopper** I can **add an item to my shopping cart** so that **I can purchase an item**.

**Acceptance Criteria**: Users can add items to their shopping bag.

#29   EPIC 4 Purchasing & Checkout

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create bag app, 
- [x] create add_to_bag view
- [x] create template
- [x] test add to bag is working
