### ISSUE TITLE
USER STORY: View a display of the products

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#2]
As a **shopper** I can **view a display of the products** so that **I can easily see and select from the displayed products**

**Comment by DaveCaulfield** [comment]
#Tasks

- [] create a products app &  model
- [] create a products view,  template and url
- [] style the products.html page
