### ISSUE TITLE
USER STORY: Add payment details

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#20]
As a **shoppper** I can **add my details** so that **I make a purchase easily**

**Acceptance Criteria**: Users can easily input their details

#29   EPIC 4 Purchasing & Checkout

**Comment by DaveCaulfield** [comment]
**#Tasks:**


- [x] create checkout app
- [x] create order and orderlineitem models
- [x] add views and order form for details
- [x]  create templates
- [x] test its working
