### ISSUE TITLE
USER STORY: Confirmation of purchase

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#22]
As a **shopper** I can **get confirmation of my purchase** so that **I can keep record of my purchases**

**Acceptance Criteria**: Users can receive a success message and can see their order detail information.

#29   EPIC 4 Purchasing & Checkout

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] add checkout success view
- [x] create and style checkout success template
- [x] test checkout success
