### ISSUE TITLE
USER STORY: Add a product

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#23]
As a **site admin** I can **add a product** so that **I can add items to the shop**.

**Acceptance Criteria**: Site admins can add a product and have it display in the the online shop.

#30   EPIC 5 Site administration

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create add product view.
- [x] create add product url and customize admins nav menu
- [x] create add product template.
- [x] add css to add product page
- [x] text backend and front end
