### ISSUE TITLE
USER STORY: Edit a product

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#24]
As a **site admin** I can **edit a product** so that **I can update item details**.

**Comment by DaveCaulfield** [comment]
#**#Tasks:**

- [x] create edit product view.
- [x] create edit product url 
- [x] create edit product template.
- [x] add css to edit product page
- [x] text backend and front end
