### ISSUE TITLE
USER STORY: Delete a product

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#25]
As a **site admin** I can **delete a product** so that **I can remove items from the shop**.

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create delete product view.
- [x] create delete product url 
- [x] text backend and front end
