### ISSUE TITLE
USER STORY: View a category of products

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#3]
As a **shopper** I can **view a category of products** so that **I can easily see a type of product that I am interested in.**

**Acceptance Criteria**: Users can easily see the available products in a selected category of product on mobile and large screen sizes.

#26 EPIC 1 Viewing and Navigation

**#Tasks:**

- [x] create a category model
- [x] add the category filtering into the all_products view
- [x] finish styling the products.html page
