### ISSUE TITLE
USER STORY: Add a shop

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#37]
As  the **shop owner** I can **add a shop to the site** so that **I can add any new shops that come on board or are opened**.

**Acceptance Criteria**: Shop owner can add a shop to the site

#30 Epic 5: Site Administration

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create shop model
- [x] create add shop view.
- [x] create the shop url 
- [x] create shoplist template.
- [x] add css to style the local shops page
- [x] test adding in backend and rendering on site
