### ISSUE TITLE
USER STORY: View an individual product

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#4]
As a **shopper** I can **view an individual product** so that **I can see the product details**.

**Acceptance Criteria**: Users can easily see a product details page for a product on mobile and large screen sizes.

#26 **EPIC 1** Viewing and Navigation

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create a category model
- [x] add the category filtering into the all_products view
- [x] finish styling the products.html page
