### ISSUE TITLE
USER STORY: Add, edit, delete staff details

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#40]
As  the **shop owner** I can **add, edit delete staff** so that **I can update staff details as required**.

**Acceptance Criteria**: Shop owner can add, edit and delete staff.

#30 Epic 5: Site Administration

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create staff model
- [x] create add staff view.
- [x] create the staff url 
- [x] create staff template.
- [x] add css to style staff pages
- [x] test adding, edit and delete in backend and rendering on site
