### ISSUE TITLE
USER STORY: Add, edit, delete Blog Posts

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#41]
As  the **shop owner** I can **upload, edit and delete Blog Posts** so that **I can upload and manage blog posts**.

**Acceptance Criteria**: Shop owner can upload, edit and delete Blog Posts.

#30 Epic 5: Site Administration

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create blog model
- [x] create post view
- [x] create bloglist view
- [x] create blog details view
- [x] create bloglike view
- [x] create blog template
- [x] create blog details template

- [x] test
