### ISSUE TITLE
USER STORY: View total price of cart

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#6]
As a **shopper** I can **easily see the total price of my shopping cart** so that **I can watch out for how much I'm spending**.

**Acceptance Criteria**: Users can easily see the total price of their shopping on mobile and large screen sizes.

#26 EPIC 1 Viewing and Navigation

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create bag app 
- [x ] create bag.html template & url
- [x] create views for add to bag, adjust quantity and remove item
- [x] Test that functionality and tat price adjusts accordingly
- [x] finish styling the products.html page
