### ISSUE TITLE
USER STORY: Product Reviews

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#7]
As a **shopper** I can **see any reviews left for products** so that **I can see other peoples thoughts and experiences of products purchased.**

**Acceptance Criteria**: Users can easily see any reviews left on the product detail page on mobile and large screen sizes.

#26 EPIC 1 Viewing and Navigation

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create review model
- [x] create add review View and render form in the product detail page
- [x] add styling to review area in products.html page
