### ISSUE TITLE
USER STORY: Create an account

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#8]
As a **site user** I can **create an account** so that **I can save my details for an easier shopping experience**.

**Acceptance Criteria**: Users can easily create an account

#27 EPIC 2 Account Registration & Login

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] install allauth package
- [x] update account templates
- [x] add styling for sign up and account  pages
