### ISSUE TITLE
USER STORY: Login to my account

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/liquid-boards#9]
As a **site user** I can **login to my account** so that **I can view/edit my account information**.

**Acceptance Criteria**: Users can easily sign in to their account

#27 EPIC 2 Account Registration & Login

**Comment by DaveCaulfield** [comment]
**#Tasks:**

- [x] create a profiles app and model for users name and address details
- [x] create profile view, template and url
- [x] create user profile form 
- [x] create a create/update profile model
- [x] add styling for profile page
